/**
 * MIL-STD-2525D Appendix H — Control Measure **lines** (symbol set 25).
 *
 * milsymbol does not draw these. Boundary, maneuver, and fires use 2525
 * linework (plain boundary + Field T, FLOT scallops, phase-line PL + T, arrows).
 * Other groups stay labelled stubs until we take them in turn.
 */

import type {
  ControlMeasureDef,
  ControlMeasureLineDraw,
} from "./controlMeasurePoints";

export const CONTROL_MEASURE_LINE_GROUPS = [
  "C2 lines",
  "Maneuver lines",
  "Fires lines",
  "Axis of advance",
  "Airspace control lines",
  "Maritime lines",
  "Protection lines",
  "Intelligence lines",
  "Sustainment lines",
  "Mission tasks",
] as const;

function L(
  entity: string,
  name: string,
  abbrev: string,
  group: string,
  lineDraw: ControlMeasureLineDraw,
  catalogHidden = false,
): ControlMeasureDef {
  return {
    entity,
    name,
    abbrev,
    group,
    geometry: "line",
    introducedIn: "2525D",
    lineDraw,
    ...(catalogHidden ? { catalogHidden: true } : {}),
  };
}

export const CONTROL_MEASURE_LINES: ControlMeasureDef[] = [
  L("110100", "Boundary", "", "C2 lines", "boundary"),
  L("110200", "Light line", "LL", "C2 lines", "light", true),
  L("110300", "Engineer work line", "EWL", "C2 lines", "phase", true),

  L("140100", "Forward line of own troops", "FLOT", "Maneuver lines", "flot"),
  L("140300", "Phase line", "PL", "Maneuver lines", "phase"),
  L("140400", "Forward edge of the battle area", "FEBA", "Maneuver lines", "phase"),
  L("140500", "Principal direction of fire", "PDF", "Maneuver lines", "arrow"),
  L("140600", "Direction of attack", "", "Maneuver lines", "arrow"),
  L("140601", "Direction of attack — friendly aviation", "", "Maneuver lines", "arrow"),
  L("140602", "Direction of attack — friendly main / decisive", "", "Maneuver lines", "arrow-double"),
  L("140603", "Direction of attack — friendly supporting", "", "Maneuver lines", "arrow"),
  L("140605", "Direction of attack — feint", "", "Maneuver lines", "arrow-dashed"),
  L("140700", "Final coordination line", "FCL", "Maneuver lines", "phase"),
  L("140800", "Infiltration lane", "", "Maneuver lines", "arrow"),
  L("140900", "Limit of advance", "LOA", "Maneuver lines", "phase"),
  L("141000", "Line of departure", "LD", "Maneuver lines", "phase"),
  L("141100", "Line of departure / line of contact", "LD/LC", "Maneuver lines", "phase"),
  L("141200", "Probable line of deployment", "PLD", "Maneuver lines", "phase"),
  L("141300", "Airhead line", "", "Maneuver lines", "phase"),
  L("141400", "Bridgehead line", "", "Maneuver lines", "phase"),
  L("141500", "Holding line", "", "Maneuver lines", "phase"),
  L("141600", "Release line", "RL", "Maneuver lines", "phase"),
  L("141700", "Ambush", "", "Maneuver lines", "arrow"),

  L("151401", "Axis of advance — friendly airborne / aviation", "", "Axis of advance", "arrow"),
  L("151402", "Axis of advance — attack helicopter", "", "Axis of advance", "arrow"),
  L("151403", "Axis of advance — main attack", "", "Axis of advance", "arrow"),
  L("151404", "Axis of advance — supporting attack", "", "Axis of advance", "arrow"),

  L("190100", "IFF off line", "IFF OFF", "Airspace control lines", "ends"),
  L("190200", "IFF on line", "IFF ON", "Airspace control lines", "ends"),

  L("218400", "Navigational", "NAV", "Maritime lines", "plain"),
  L("220100", "Bearing line", "", "Maritime lines", "arrow"),
  L("220101", "Bearing line — electronic", "ELNOT", "Maritime lines", "arrow"),
  L("220102", "Bearing line — electronic warfare", "EW", "Maritime lines", "arrow"),
  L("220103", "Bearing line — acoustic", "ACOU", "Maritime lines", "arrow"),
  L("220104", "Bearing line — acoustic (ambiguous)", "ACOU", "Maritime lines", "arrow"),
  L("220105", "Bearing line — torpedo", "TORP", "Maritime lines", "arrow"),
  L("220106", "Bearing line — electro-optical intercept", "EO", "Maritime lines", "arrow"),
  L("220107", "Bearing line — jammer", "JAM", "Maritime lines", "arrow"),
  L("220108", "Bearing line — radio direction finder", "RDF", "Maritime lines", "arrow"),

  L("240701", "Linear target", "", "Fires lines", "ibeam"),
  L("240702", "Linear smoke target", "SMK", "Fires lines", "ibeam", true),
  L("240703", "Final protective fire", "FPF", "Fires lines", "ibeam", true),
  L("260100", "Fire support coordination line", "FSCL", "Fires lines", "phase"),
  L("260200", "Coordinated fire line", "CFL", "Fires lines", "phase"),
  L("260300", "No-fire line", "NFL", "Fires lines", "phase"),
  L("260400", "Battlefield coordination line", "BCL", "Fires lines", "phase"),
  L("260500", "Restrictive fire line", "RFL", "Fires lines", "phase"),
  L("260600", "Munition flight path", "MFP", "Fires lines", "arrow"),

  L("270503", "Obstacle effect — fix", "FIX", "Protection lines", "plain"),
  L("270504", "Obstacle effect — turn", "TURN", "Protection lines", "plain"),
  L("271100", "Bridge or gap", "", "Protection lines", "plain"),
  L("271201", "Roadblock — planned", "", "Protection lines", "plain"),
  L("271202", "Roadblock — explosives (safe)", "", "Protection lines", "plain"),
  L("271203", "Roadblock — explosives (armed, passable)", "", "Protection lines", "plain"),
  L("271204", "Roadblock complete (executed)", "", "Protection lines", "plain"),
  L("271300", "Assault crossing", "", "Protection lines", "plain"),
  L("271500", "Ford easy", "", "Protection lines", "plain"),
  L("271600", "Ford difficult", "", "Protection lines", "plain"),
  L("280100", "Abatis", "", "Protection lines", "plain"),
  L("282003", "Overhead wire", "", "Protection lines", "plain"),
  L("290100", "Obstacle line", "", "Protection lines", "plain"),
  L("290101", "Mine line", "", "Protection lines", "plain"),
  L("290201", "Antitank obstacle — under construction", "", "Protection lines", "plain"),
  L("290202", "Antitank obstacle — completed", "", "Protection lines", "plain"),
  L("290203", "Antitank obstacle — reinforced with AT mines", "", "Protection lines", "plain"),
  L("290204", "Antitank wall", "", "Protection lines", "plain"),
  L("290301", "Wire — unspecified", "", "Protection lines", "plain"),
  L("290302", "Wire — single fence", "", "Protection lines", "plain"),
  L("290303", "Wire — double fence", "", "Protection lines", "plain"),
  L("290304", "Wire — double apron fence", "", "Protection lines", "plain"),
  L("290305", "Wire — low wire fence", "", "Protection lines", "plain"),
  L("290306", "Wire — high wire fence", "", "Protection lines", "plain"),
  L("290307", "Wire — single concertina", "", "Protection lines", "plain"),
  L("290308", "Wire — double strand concertina", "", "Protection lines", "plain"),
  L("290309", "Wire — triple strand concertina", "", "Protection lines", "plain"),
  L("290500", "Trip wire", "", "Protection lines", "plain"),
  L("290600", "Lane", "", "Protection lines", "plain"),
  L("290700", "Ferry", "", "Protection lines", "plain"),
  L("290800", "Raft site", "", "Protection lines", "plain"),
  L("290900", "Fortified line", "", "Protection lines", "ends"),
  L("291000", "Fighting position", "", "Protection lines", "plain"),

  L("300100", "Intelligence coordination line", "ICL", "Intelligence lines", "ends"),

  L("330100", "Moving convoy", "", "Sustainment lines", "arrow"),
  L("330200", "Halted convoy", "", "Sustainment lines", "plain"),
  L("330300", "Main supply route", "MSR", "Sustainment lines", "ends"),
  L("330301", "Main supply route — one-way", "MSR", "Sustainment lines", "arrow"),
  L("330302", "Main supply route — two-way", "MSR", "Sustainment lines", "plain"),
  L("330303", "Main supply route — alternating", "MSR", "Sustainment lines", "plain"),
  L("330400", "Alternate supply route", "ASR", "Sustainment lines", "ends"),
  L("330401", "Alternate supply route — one-way", "ASR", "Sustainment lines", "arrow"),
  L("330402", "Alternate supply route — two-way", "ASR", "Sustainment lines", "plain"),
  L("330403", "Alternate supply route — alternating", "ASR", "Sustainment lines", "plain"),

  L("340200", "Breach", "", "Mission tasks", "arrow"),
  L("340500", "Clear", "", "Mission tasks", "arrow"),
  L("340600", "Counterattack", "", "Mission tasks", "arrow"),
  L("340700", "Counterattack by fire", "", "Mission tasks", "arrow"),
  L("340800", "Delay", "", "Mission tasks", "arrow"),
  L("341100", "Fix", "", "Mission tasks", "arrow"),
  L("341200", "Follow and assume", "", "Mission tasks", "arrow"),
  L("341300", "Follow and support", "", "Mission tasks", "arrow"),
  L("342000", "Retire / retirement", "", "Mission tasks", "arrow"),
  L("342201", "Cover", "", "Mission tasks", "arrow"),
  L("342202", "Guard", "", "Mission tasks", "arrow"),
  L("342203", "Screen", "", "Mission tasks", "arrow"),
  L("342300", "Seize", "", "Mission tasks", "arrow"),
  L("342400", "Withdraw", "", "Mission tasks", "arrow"),
  L("342500", "Withdraw under pressure", "", "Mission tasks", "arrow"),
  L("342900", "Advance to contact", "", "Mission tasks", "arrow"),
  L("343000", "Capture", "", "Mission tasks", "arrow"),
  L("343100", "Conduct exploitation", "", "Mission tasks", "arrow"),
  L("343300", "Demonstration", "", "Mission tasks", "arrow"),
  L("343500", "Envelop", "", "Mission tasks", "arrow"),
  L("343600", "Escort", "", "Mission tasks", "arrow"),
  L("343700", "Exfiltrate", "", "Mission tasks", "arrow"),
  L("343800", "Infiltrate", "", "Mission tasks", "arrow"),
  L("344000", "Pursue", "", "Mission tasks", "arrow"),
];
